# Generated by Django 5.2.13 on 2026-04-07 18:31

from django.db import migrations, models


def seed_categories_from_products(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Product = apps.get_model('inventory', 'Product')

    seen_names = set()
    for product in Product.objects.exclude(category__isnull=True).exclude(category__exact=""):
        normalized_name = product.category.strip()
        if not normalized_name:
            continue
        lookup_key = normalized_name.lower()
        if lookup_key in seen_names:
            continue
        seen_names.add(lookup_key)
        Category.objects.create(name=normalized_name)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RunPython(seed_categories_from_products, migrations.RunPython.noop),
    ]
